services:
  postgres:
    image: postgres:15-alpine
    container_name: secureauth_postgres
    environment:
      POSTGRES_USER: secureauth
      POSTGRES_PASSWORD: secureauth_password
      POSTGRES_DB: secureauth_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./scripts/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U secureauth -d secureauth_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - secureauth_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: secureauth_redis
    command: redis-server --appendonly yes --requirepass secureauth_redis_password
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'secureauth_redis_password', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - secureauth_network
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secureauth_api
    env_file:
      - .env
    environment:
      # Override untuk development
      DATABASE_URL: postgresql+asyncpg://secureauth:secureauth_password@postgres:5432/secureauth_db
      REDIS_URL: redis://:secureauth_redis_password@redis:6379/0
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./app:/app/app:delegated
      - ./alembic:/app/alembic:delegated
      - ./logs:/app/logs:delegated
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 10 &&
        python -m alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug
      "
    networks:
      - secureauth_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: secureauth_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    networks:
      - secureauth_network
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: secureauth_mailhog
    ports:
      - '1025:1025'  # SMTP server
      - '8025:8025'  # Web UI
    networks:
      - secureauth_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  secureauth_network:
    driver: bridge
    name: auth-api-network